name: Tests
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
env:
  MIX_ENV: test
jobs:
  build:
    name: Build test environment
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/elixir-setup
      - name: Compile project
        run: mix compile
  unit-test:
    needs: build
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/elixir-setup
      - name: Run tests
        run: mix test
  e2e:
    needs: build
    name: E2E Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/elixir-setup
      - name: Setup assets
        run: mix assets.setup
      - name: Build assets
        run: mix assets.build
      - name: Setup ChromeDriver
        uses: nanasess/setup-chromedriver@v2
      - name: Start ChromeDriver
        run: |
          export DISPLAY=:99
          chromedriver --port=4444 &
          sudo Xvfb :99 -screen 0 1280x1024x24 > /dev/null 2>&1 &
      - name: Run E2E tests
        run: mix test.e2e
